version: '3.8'

services:
  elasticsearch:
    image: suy3024/elasticsearch:${ELASTICSEARCH_IMAGE_VERSION:-0.0.0}
    build:
      context: .
      dockerfile: Dockerfile.elasticsearch
    container_name: elasticsearch
    restart: on-failure
    volumes:
      - esdata:/usr/share/elasticsearch/data:rw
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - cluster.name=elastic-cluster
      - discovery.type=single-node
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false

  kibana:
    image: docker.elastic.co/kibana/kibana:7.16.2
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    depends_on:
      - elasticsearch

volumes:
  esdata: {}
  eslog: {}
